name: em

channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.2
  - git
  - simpeg
  - pyvista
  - dill
  - jupyter
  - ipywidgets
  - pip:
    - git+https://github.com/kujaku11/mth5.git
    - git+https://github.com/kujaku11/mt_metadata.git
    - git+https://github.com/MTgeophysics/mtpy.git@v2