
name: TestingInConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda env create -f environment.yml
        source activate em
        git clone https://github.com/simpeg/simpeg
        cd simpeg
        git checkout -f tiled_fdem_nsem
        pip install -e .
        cd ..
        git clone https://github.com/kujaku11/mth5.git
        cd mth5
        pip install -e .
        cd ..
        git clone https://github.com/kujaku11/mt_metadata.git
        cd mt_metadata
        pip install -e .
        cd ..
        git clone git+https://github.com/MTgeophysics/mtpy.git
        cd mtpy
        git check out -f v2
        pip install -e .
        cd ..
        pip install -r requirements_dev.txt
    - name: Run Tests
      shell: bash
      run: |
        source activate em
        conda list
        pytest .
